### ISSUE TITLE
Project title

### ISSUE THREAD

**Issue by bangnoise** [disguise-one/hap-encoder-adobe-cc#10]
We should change the title of this project now - the sooner it's changed, the less confusion.

Yet another confused user

https://twitter.com/killiantimsit/status/1045611946760855552?s=21

**Comment by exscriber** [comment]
In my opinion - better to list all currently supported software in title.
Something like: "Hap Exporter for Adobe Premiere and Adobe Media Encoder CC 2018"
Maybe with additianal note like:
This plugin not support AE direct Export yet, but you can add Sequence to Adobe Media Encoder Queue - and render it in AME.

It`s not about code-name-cebab, just brand name title: first thing customers see.
Because otherwise codename will looks like: adobe-mediacore-hap-exporter, but who cares?

**Comment by bangnoise** [comment]
@exscriber the title is short and forms part of the URL.

@GregBakker I'd go with hap-encoder-adobe-cc myself, encode is p'haps too curtailed.

Maybe we can change it now right now rather than waiting to avoid confusing anyone else?

**Comment by exscriber** [comment]
@bangnoise i agree with short URL like hap-encoder-adobe-cc on github.

I just want to mention that many customers came by direct link to releases page.
So good description on releases (downloads) page is as important as URL.

**Comment by GregBakker** [comment]
Ok, let's
 * make a note at the top level that it's for Media Encoder, Premiere, and AE via Media Encoder.
 * change the repo name to hap-encoder-adobe-cc
 * add a description / longer title as suggested by @exscriber

Having said all of this - I've just had a report from a friend that it errors out on installation if Premiere isn't installed; even if you're always using it from Media Encoder - so I'll have to make a known issue on that too. Needs more testing.

**Comment by GregBakker** [comment]
disguise-one org will have to change the name of the repo; have put the wheels in motion for that :)

I'll make the top level changes so that those who read / install it will know it's supposed to work on AME, Premiere and AE via AME.

**Comment by twhittock** [comment]
Repository has been renamed to hap-encoder-adobe-cc. Thanks.
