### ISSUE TITLE
Installation error if Premiere is missing

### ISSUE THREAD

**Issue by bangnoise** [disguise-one/hap-encoder-adobe-cc#13]
@GregBakker said "I've just had a report from a friend that it errors out on installation if Premiere isn't installed; even if you're always using it from Media Encoder - so I'll have to make a known issue on that too. Needs more testing."

**Comment by bangnoise** [comment]
Which platform @GregBakker ? I'll look if macOS.

**Comment by GregBakker** [comment]
It was windows; I don't have details on which version. Also I believed other people had tried with AME alone and I haven't a clean machine to verify the report yet.

However it *is* likely a problem at least for some people, and we need to find whatever registry key AME uses to find its plugins - worst case we might have to create the Premiere one ourselves.

**Comment by GregBakker** [comment]
I'll see if disguise QA can reproduce the issue.

**Comment by GregBakker** [comment]
In progress :)

**Comment by GregBakker** [comment]
Confirmed - now need to find out how an installer should work out where to put its files.

**Comment by exscriber** [comment]
Maybe for fallback in case no Premiere detected: (or even general install rule)
1) don`t install presets, because plugin have default settings (i must check on clear install, but hope they init ok)
2) intall plugin at "%ProgramFiles%/Adobe/Common/Plug-ins/7.0/MediaCore/Hap" direct path, not from registry
cause Adobe is 64bit anyway, and MediaCore 7.0 version seems to hold for now... (2017/2018/2019)

**Comment by GregBakker** [comment]
I've added a fix that does this, undergoing testing. Can be found on the releases page as the 1.0.9-RC1 prerelease. As suggested it tries to drop it in the appropriate spot rather than interrogate the registry, as there doesn't seem to be any good way of doing that atm.
